module.exports = {
    onayemoji: "TIK EMOJI",
    redemoj: "CARPI EMOJI",
    unlememoji: "UNLEM EMOJI",
    shewn:"SPEAR EMOJI",
    loadingemoji:"LOADIN EMOJI",
    galb:"KALP EMOJI",
    sıfır:"0",
    bir:"1",
    iki:"2",
    üc:"3",
    dört:"4",
    beş:"5",
    altı:"6",
    yedi:"7",
    sekiz:"8",
    dokuz:"9",
}